import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <Script
          id="applepay"
          strategy="lazyOnload"
          src="https://applepay.cdn-apple.com/jsapi/v1/apple-pay-sdk.js"
        ></Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
